json.id real_estate.id
json.created_at real_estate.created_at
json.updated_at real_estate.updated_at
json.street real_estate.street
json.city real_estate.city
json.zip real_estate.zip
json.state real_estate.state
json.beds_number real_estate.beds_number
json.square_feet real_estate.square_feet
json.building_type real_estate.building_type
json.sale_date real_estate.sale_date
json.price real_estate.price
json.latitude real_estate.latitude
json.longitude real_estate.longitude
